package com.sierraazul.controlpagosapi.dto;


public class PagosDto {
    public Long id;
    public String cut;
    public String fecha;
    public String tipoDocumento;
    public String nro;
    public String ftefto;
    public String monto;
    public String areaUsuaria;
    public String fechaRecepcion;
    public String nombreProveedor;
    public Integer orden;
    public Integer siaf;
    public String clasificador;
    public String responsableControlPrevio;
    public String tipoOrdenServicioCompra;
    public String region;
    public String ruc;
    public String comprobante;
    public String nroDocumento;
    public String fechaEmision;
    public String penalidad;
    public String montoPenalidad;
    public String numeroPago;
    public String observacionPagos;
    public String estadoDocumento;
    public String fechaEntregaContabilidad;
    public String ultimaModificacion;
    public String fechaContabilidad_1;
    public String fechaContabilidad_2;
    public String estadoControlPrevio;
    public String responsableContabilidad;
    public String comprobanteContabilidad;
    public String montoContabilidad;
    public String retencionContabilidad;
    public String detraccionContabilidad;  
    public String penalidadContabilidad;
    public String situacionExpediente;
    public String porRevisar;
    public String estadoDevengadoSiaf;
    public String tipoObservacion;
    public String concepto;
    public String areaCorrige;
    public String fechaEntrega;
    public String fechaDevolucion;
    public String estadoValidacion;
    public String fechaDevengado;
    public String montoDevengadoAprobado;
    public String verificaRepeticion;
    public String validaSiaf;
    public String comprobantePagoTesoreria;
    public String montoTotalCps;
    public String observacion;
    public String ubicacion;       
}
